name: Test angular app

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Setup
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm test

      - name: E2E Test
        run: ng e2e

      - name: Pre-release through Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
